---
- name: TVM Deployment
  hosts: localhost
  tasks:

  - name: add trilio helm repo
    command: helm repo add trilio http://51.161.115.96:8081/repository/trilio/ --username admin --password trilio

  - name: repo update  
    shell: helm repo update

  - name: Install triliovault RHV 
    command: helm install tvr trilio/tvault --create-namespace  --dependency-update   -f /opt/ansible/values.yaml --set namespace=trilio 

  - name: Install mariadb
    command: helm install mariadb trilio/mariadb -n trilio

  - name: Create a directory /opt/manifest/ca if it does not exist
    ansible.builtin.file:
      path: /opt/manifest/ca
      state: directory
      mode: '0775'

  - name: check if CA  exists
    stat: 
      path: /opt/manifest/ca/CA.pem
    register: ca_pem

  - name: Create CA and Certs
    shell: |
      openssl genrsa -des3 -out /opt/manifest/ca/CA.key -passout pass:52T8FVYZJse  2048 
      openssl req -x509 -new -nodes -key /opt/manifest/ca/CA.key -passin pass:52T8FVYZJse  -sha256 -days 1825 -out /opt/manifest/ca/CA.pem -batch
      openssl genrsa -out /opt/manifest/ca/workloadmgr.key 2048
      openssl req -new -key /opt/manifest/ca/workloadmgr.key -out /opt/manifest/ca/workloadmgr.csr -batch
    when: ca_pem.stat.exists == False
    

  - name: signed the certificate
    shell: |
      echo " 
          authorityKeyIdentifier=keyid,issuer
          basicConstraints=CA:FALSE
          keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
          subjectAltName = @alt_names
          [alt_names]
          DNS.1 = tvault.com " > /opt/manifest/ca/workloadmgr.ext 
          
      openssl x509 -req -in /opt/manifest/ca/workloadmgr.csr -CA /opt/manifest/ca/CA.pem -CAkey /opt/manifest/ca/CA.key -CAcreateserial -out /opt/manifest/ca/workloadmgr.cert -days 1825 -sha256 -extfile /opt/manifest/ca/workloadmgr.ext  -passin pass:52T8FVYZJse

  - name: create secrets for CA
    shell: kubectl create secret generic ca-certs --from-file=pem_content=/opt/manifest/ca/CA.pem  --from-file=key_content=/opt/manifest/ca/CA.key -n trilio
    ignore_errors: True

  - name: create secrets for Ingress
    shell: kubectl create secret tls tvault-ingress-tls --namespace trilio --key /opt/manifest/ca/workloadmgr.key --cert /opt/manifest/ca/workloadmgr.cert
    ignore_errors: True

 
