---

- name: restart services
  shell: |
        systemctl restart docker


- name: Copy k8s_token_file_worker
  copy: 
    src: "/tmp/join-worker-command"
    dest: "/tmp/join-worker-command.sh"
    mode: "0750"
  
- name:  Join the worker plane to cluster 
  become: true
  command: sh /tmp/join-worker-command.sh
  args:
    creates: "{{ k8s_kubelet_config }}"
  async: 900
  poll: 5
  
- name: copy manifest directory among nodes
  synchronize:
    src: /opt/manifest/
    dest: /opt/manifest/
